version: '3.8'
services:
  drupal:
    build: .
    ports:
      - "8080:80"
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: password

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites: